Time: 300
#Time (in seconds) between each broadcast.
#300 seconds (default) = 5minutes
#600 seconds = 10 minutes
#1800 seconds = 30 minutes
#3600 seconds = 60 hours (1 hour)

TopBorder: '-----------------------------------'
Broadcasts:
  - 'Come and have a chat on TeamSpeak using the ip: ts.testserver.org!'
  - 'You are playing on: Test Server!'
  - 'Remember to check out our forums at www.testserver.org!'
BottomBorder: '-----------------------------------'
